train: C:/Users/PAUL/OneDrive - ESME/Documents/botique/2025/balise_2025/data_set_training_debug/images/train
val: C:/Users/PAUL/OneDrive - ESME/Documents/botique/2025/balise_2025/data_set_training_debug/images/val
test: C:/Users/PAUL/OneDrive - ESME/Documents/botique/2025/balise_2025/data_set_training_debug/images/test

nc: 2
names: ['canette', 'planche']
